project_id = "uuamwkahckzufscqkviz"

[functions.exchange-token]
verify_jwt = false

[functions.ai-bot-process-knowledge]
verify_jwt = false

[functions.ai-bot-upload-file]
verify_jwt = true

[functions.ai-bot-chat]
verify_jwt = false

[functions.ai-bot-retrain]
verify_jwt = true

[functions.ai-bot-save-lead]
verify_jwt = false

[functions.ai-bot-track-appointment]
verify_jwt = false

[functions.ai-bot-webhook-trigger]
verify_jwt = false

[functions.ai-bot-send-invite]
verify_jwt = true

[functions.ab-create-checkout]
verify_jwt = true

[functions.ab-stripe-webhook]
verify_jwt = false

[functions.ab-send-payment-email]
verify_jwt = false

[functions.ab-manage-subscription]
verify_jwt = true
